services:
  mariadb:
    image: 'mariadb:latest'
    container_name: 'mariadb'
    environment:
      - 'MARIADB_DATABASE=saltybread'
      - 'MARIADB_PASSWORD=1234'
      - 'MARIADB_ROOT_PASSWORD=1234'
      - 'MARIADB_USER=admin'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'

  redis:
    image: 'redis:latest'
    container_name: 'redis'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'backend'
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started