services:
  jenkins:
    build:
      context: ./docker
    container_name: 'jenkins'
    restart: always
    privileged: true
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./docker/volumes/jenkins/var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - saltybread

  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: 'portainer'
    privileged: true
    restart: always
    volumes:
      - ./docker/volumes/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - saltybread

  proxy:
    image: nginx:latest
    container_name: 'proxy'
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - jenkins
      - portainer
    networks:
      - saltybread
networks:
  saltybread:
    driver: bridge