services:
  mariadb:
    image: 'mariadb:latest'
    container_name: 'mariadb'
    environment:
      - 'MARIADB_DATABASE=saltybread'
      - 'MARIADB_PASSWORD=1234'
      - 'MARIADB_ROOT_PASSWORD=1234'
      - 'MARIADB_USER=admin'
    ports:
      - '3306:3306'
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'backend'
    ports:
      - 8000:8000
    depends_on:
      - mariadb
      - rabbitmq
      - redis