services:
  mariadb:
    image: 'mariadb:latest'
    container_name: 'mariadb'
    environment:
      - 'MARIADB_DATABASE=saltybread'
      - 'MARIADB_PASSWORD=1234'
      - 'MARIADB_ROOT_PASSWORD=1234'
      - 'MARIADB_USER=admin'
    options: --health-cmd="healthcheck.sh --su-mysql --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'

  redis:
    image: 'redis:latest'
    container_name: 'redis'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'backend'
    depends_on:
      mariadb:
        condition: service_started
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started