services:
  jenkins:
    image: 'jenkins/jenkins:latest'
    container_name: 'jenkins'
    environment:
      - 'MARIADB_DATABASE=saltybread'
      - 'MARIADB_PASSWORD=1234'
      - 'MARIADB_ROOT_PASSWORD=1234'
      - 'MARIADB_USER=admin'
    ports:
      - '8080:8080'
    volumes:
      - ./docker/jenkins/var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: 'portainer'
    privileged: true
    ports:
      - '19000:9000'
    volumes:
      - ./docker/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock