services:
  mariadb:
    image: 'mariadb:latest'
    container_name: 'mariadb'
    restart: always
    environment:
      - 'MARIADB_DATABASE=saltybread'
      - 'MARIADB_PASSWORD=1234'
      - 'MARIADB_ROOT_PASSWORD=1234'
      - 'MARIADB_USER=admin'
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - network
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'rabbitmq'
    restart: always
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    networks:
      - network
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    restart: always
    networks:
      - network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'backend'
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - network
networks:
  network:
    name: saltybread
    external: true